AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.3
  SuggestExtensions: false
  Exclude:
    - 'test_*.rb'  # Exclude ad-hoc integration test scripts
    - 'scripts/**/*'  # Exclude integration test scripts
    - 'local/**/*'  # Exclude local test scripts
    - 'vendor/**/*'  # Exclude vendored gems (CI bundles here)

# Allow longer methods for complex logic
Metrics/MethodLength:
  Max: 50

# Allow higher complexity for response handling
Metrics/AbcSize:
  Max: 25

# Disable class length checks so rubocop doesn't complain that we implement all of Hyperliquid's endpoints
Metrics/ClassLength:
  Enabled: false

# Allow longer blocks in specs and gemspec - this is normal for tests and gem configs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

# Exchange API methods require many parameters
Metrics/ParameterLists:
  Exclude:
    - 'lib/hyperliquid/exchange.rb'

# Allow higher complexity for order type conversion logic and WS message handling
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/hyperliquid/exchange.rb'
    - 'lib/hyperliquid/ws/client.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/hyperliquid/exchange.rb'
