AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.3

# Allow longer methods for complex logic
Metrics/MethodLength:
  Max: 50

# Allow higher complexity for response handling
Metrics/AbcSize:
  Max: 25

# Allow longer blocks in specs - this is normal for tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'